# Generated by Django 4.2.11 on 2024-05-11 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applications_common', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.applications')),
                ('employes_common', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.employes')),
                ('files_common', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.files')),
            ],
        ),
    ]
