# Generated by Django 4.2.11 on 2024-05-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('a_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('application_num', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=15)),
                ('datetime', models.DateTimeField()),
                ('name', models.CharField(max_length=30)),
                ('application_text', models.CharField(blank=True, max_length=300, null=True)),
                ('prop_solution', models.CharField(blank=True, max_length=300, null=True)),
                ('answer', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'applications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('email_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('possitionj', models.BooleanField()),
            ],
            options={
                'db_table': 'employes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('f_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('owner', models.BooleanField()),
                ('path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'files',
                'managed': False,
            },
        ),
    ]
